### ISSUE TITLE
projects page does not build (and maybe members)

### ISSUE THREAD

**Issue by handicraftsman** [hellomouse/newsite#4]
![screenshot_20181214-121118_firefox nightly](https://user-images.githubusercontent.com/6382804/49997164-85858780-ff99-11e8-9c72-cbfe1bfd6056.jpg)
@wolfy1339 that was your commit.

**Comment by wolfy1339** [comment]
I saw that. I'm fixing that along with adding eslint.

**Comment by handicraftsman** [comment]
oh ok
